#run mobilenet
bsub -q gpu-long -app nvidia-gpu -env LSB_CONTAINER_IMAGE=nvcr.io/nvidia/tensorflow:21.11-tf2-py3 -gpu num=2:j_exclusive=yes -R "affinity[thread*4] select[mem>32384] rusage[mem=32384]"  -R "select[hname!=dgxws01]"    -R "select[hname!=dgxws02]"    -R "select[hname!=agn04]" -R "select[hname!=agn05]"   -R "select[hname!=hgn02]"     -R "select[hname!=hgn03]"  -R "select[hname!=hgn07]"    -R "select[hname!=hgn08]"   -R "select[hname!=hgn09]"    -R "select[hname!=hgn10]"    -R "select[hname!=hgn11]"     -R "select[hname!=hgn12]" -o out1Imgnet.%J -e err1Imgnet.%J  python full_learning_imagenet303.py --student_nl relu --dropout 0.0 --rnn_dropout 0.0 --conv_rnn_type lstm --n_samples 4 --max_length 4 --epochs 10 --int_epochs 0 --teacher_model keras_mobilenet_v2 --teacher_model keras_mobilenet_v2 --student_block_size 3 --time_pool average_pool --student_version 3 --resnet_mode --decoder_optimizer SGD --val_set_mult 1 --res 56 --verbose 2 --broadcast 0 --dataset_dir /shareDB/imagenet201/5.0.0/ --centered_offsets --amp 12 --rggb_ext_type 0 --kernel_size 3 --no-rggb_mode --num_feature 96 --stu_steps_per_epoch 10000 --preprocessing keras_mobilenet_v2


#save stuff into np
bsub -q gpu-short -app nvidia-gpu -env LSB_CONTAINER_IMAGE=nvcr.io/nvidia/tensorflow:21.11-tf2-py3 -gpu num=1:j_exclusive=yes -R "affinity[thread*1] select[mem>32384] rusage[mem=32384]"  -R "select[hname!=dgxws01]"    -R "select[hname!=dgxws02]"    -R "select[hname!=agn04]" -R "select[hname!=agn05]"   -R "select[hname!=hgn02]"     -R "select[hname!=hgn03]"  -R "select[hname!=hgn07]"    -R "select[hname!=hgn08]"   -R "select[hname!=hgn09]"    -R "select[hname!=hgn10]"    -R "select[hname!=hgn11]"     -R "select[hname!=hgn12]" -o out1Imgnet.%J -e err1Imgnet.%J  python full_learning_imagenet303_keras_to_numpy.py --student_nl relu --dropout 0.0 --rnn_dropout 0.0 --conv_rnn_type lstm --n_samples 5  --max_length 4   --epochs 4 --int_epochs 0 --teacher_model  keras_mobilenet_v2 --teacher_model keras_mobilenet_v2 --student_block_size 3 --time_pool average_pool --student_version 3 --resnet_mode --decoder_optimizer SGD --val_set_mult 1 --res 56 --verbose 1 --broadcast 0 --dataset_dir /shareDB/imagenet201/5.0.0/  --centered_offsets --amp 12 --rggb_ext_type 0 --kernel_size 3   --no-rggb_mode  --num_feature 96 --preprocessing  keras_mobilenet_v2 --pretrained_student_path  saved_models/noname_j919244_t1661455557_feature/noname_j919244_t1661455557_feature_net_ckpt --pretrained_decoder_path  saved_models/noname_j383765_t1661630648_feature/noname_j383765_t1661630648_saved_models/decoder_trained_model_fix0/ --out_weight_pickle_file  j383765_weights.pkl


#copy output files from wexac:
scp  arivkind@access.wexac.weizmann.ac.il:./imagewalker/teacher_student/out1Imgnet* drc_result_dirs/imagenet/